variables:
  MYSQL_DATABASE: $MYSQL_DB
  MYSQL_ROOT_PASSWORD: $MYSQL_PASS
  MYSQL_USER: $MYSQL_USER
  MYSQL_PASSWORD: $MYSQL_PASS

default:
  image: ubuntu:22.04
  services:
    - mysql:8.0
  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - apt-get update
    - apt-get install -y python3.11 python3.11-venv python3-pip
    - apt-get install -y mysql-client libmysqlclient-dev
    - apt-get install -y pkg-config build-essential
    - python3.11 -m pip install --upgrade pip

migrations:
  stage: build
  script:
    - cd Backend
    - python3.11 -m pip install -r requirements.txt
    - python3.11 manage.py migrate
    - python3.11 manage.py check

django-tests:
  stage: test
  script:
    - cd Backend
    - python3.11 -m pip install -r requirements.txt
    - echo "GRANT ALL on *.* to '${MYSQL_USER}';" | mysql -u root --password="${MYSQL_ROOT_PASSWORD}" -h mysql
    - python3.11 manage.py test

deploy:
  stage: deploy
  script:
    - echo "No deployment configured!"
  environment: production