variables:
  MYSQL_DATABASE: test_db
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: test_user
  MYSQL_PASSWORD: test_pass

  DB_NAME: test_db
  DB_USER: test_user
  DB_PASSWORD: test_pass
  DB_HOST: mysql
  DB_PORT: "3306"

default:
  image: ubuntu:22.04
  services:
    - name: mysql:8.0
      alias: mysql
  cache:
    paths:
      - ~/.cache/pip/

  before_script:
    - apt-get update
    - apt-get install -y python3.11 python3.11-venv python3-pip python3.11-dev
    - apt-get install -y mysql-client libmysqlclient-dev
    - apt-get install -y pkg-config build-essential
    - python3.11 -m pip install --upgrade pip

stages:
  - build
  - lint
  - test
  - deploy

migrations:
  stage: build
  script:
    - cd Backend
    - python3.11 -m pip install -r requirements.txt
    - echo "Waiting for MySQL..."
    - |
      i=0
      until mysqladmin ping -h "mysql" --silent; do
        i=$((i+1))
        if [ $i -gt 60 ]; then
          echo "MySQL not ready"
          exit 1
        fi
        sleep 2
      done
    - python3.11 manage.py migrate
    - python3.11 manage.py check

Backend-lint:
  stage: lint
  script:
    - cd Backend
    - python3.11 -m pip install -r requirements.txt
    - python3.11 -m pip install flake8
    - flake8 . 


django-tests:
  stage: test
  script:
    - cd Backend
    - python3.11 -m pip install -r requirements.txt
    - pytest

deploy:
  stage: deploy
  script:
    - echo "No deployment configured!"
  environment: production