image: python:3.11

stages:
  - lint
  - build
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V
  - pip install --upgrade pip
  - pip install -r requirements.txt

# -------------------
# Lint (PEP8 check)
# -------------------
lint:
  stage: lint
  script:
    - pip install flake8
    - flake8 .
  allow_failure: true


# -------------------
# Migrations + checks
# -------------------
build:
  stage: build
  script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py check


# -------------------
# Django tests
# -------------------
test:
  stage: test
  script:
    - python manage.py test