[pytest]
DJANGO_SETTINGS_MODULE = first_job_navigator.test_settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = --ds=first_job_navigator.test_settings --import-mode=importlib