# Generated by Django 5.2.6 on 2026-04-09 15:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MoveOutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_postcode", models.CharField(max_length=10)),
                ("area_name", models.CharField(blank=True, max_length=255)),
                ("area_code", models.CharField(blank=True, max_length=32)),
                (
                    "monthly_income",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "monthly_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "estimated_monthly_rent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "disposable_income",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "rent_ratio_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("readiness_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("borderline", "Borderline"),
                            ("needs_improvement", "Needs Improvement"),
                            ("not_ready", "Not Ready"),
                        ],
                        default="not_ready",
                        max_length=25,
                    ),
                ),
                (
                    "crime_level",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("property_listings", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_out_plan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Move Out Plan",
                "verbose_name_plural": "Move Out Plans",
            },
        ),
    ]
