# Generated by Django 5.2.6 on 2026-04-01 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "pension_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "student_loan_plan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plan1", "Plan 1"),
                            ("plan2", "Plan 2"),
                            ("plan4", "Plan 4"),
                            ("plan5", "Plan 5"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "tax_region",
                    models.CharField(
                        choices=[("england", "England"), ("scotland", "Scotland")],
                        default="england",
                        max_length=20,
                    ),
                ),
                ("income_tax", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "national_insurance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "student_loan",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pension",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("net_annual", models.DecimalField(decimal_places=2, max_digits=12)),
                ("net_monthly", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
